### ISSUE TITLE
Issue loading InputStream over the network

### ISSUE THREAD

**Issue by elemongw** [exbin/exbin-utils-java#1]
When using ByteArrayEditableData's loadFromStream [1] to load an InputStream over the network, it returns with no data having been read. This is because it uses InputStream.available to decide if there is still data to read. However, available() is used to get how many bytes you can read from the InputStream without blocking which, when loading files over the network, will be 0.

An alternative implementation could potentially use the return value of read instead to make this decision.

[1] https://github.com/exbin/exbin-auxiliary-java/blob/f1d5d05b3e6f8e463dfaf3ef73ab1e0e98a656ee/modules/paged_data/src/main/java/org/exbin/auxiliary/paged_data/ByteArrayEditableData.java#L324-L335

**Comment by hajdam** [comment]
Hi,
thank you for reporting this. I didn't read contract of the method properly and incorrectly assumed it would return 1 when size cannot be determined :-/

I'll try to fix this with my next PR when adding binary editor to muCommander.
